### ISSUE TITLE
Make `weighted-highway-exit-v0` environment

### ISSUE THREAD

**Issue by GustavGroenborg** [GustavGroenborg/HighwayEnv#6]
Make an environment that takes simulates the ego vehicle spawning on the highway and then exits the highway onto an exit ramp. For inspiration to the solution please look at `envs/exit_env.py`. **Remember** that the environment must use `WeightedRoadnetwork` to construct the road network.

## Tasks
- [ ] Derive from `ExitEnv`
- [ ] Override the following functions:
   - [ ] `ExitEnv._reward(action)`
   - [ ] `ExitEnv._rewards(action)`
   - [ ] `ExitEnv._create_road(...)`
   - [ ] `ExitEnv._create_vehicles()`
- [ ] Use `WeightedRoadnetwork` to construct the graph.
- [ ] Make spawning algorithm, to spawn a random number of vehicles.
   - [ ] Vehicles must be spawned on exit ramp ahead of the ego vehicle.
   - [ ] Vehicles must be spawned on the highway.
   - [ ] The number of vehicles spawned must be based on the instance key-value argument `ExitEnv.config["vehicles_count"]`
- [ ] Add lane-type to each edge.
- [ ] Add weight to each edge.
- [ ] Make a `networkx` drawing over the environment.
   * Look to `envs/env_drawing.ipynb` for inspiration.
- [ ] Write the reward function.
   * It could possibly include the following:
      * `ControlledVehicle.headway_evaluation()`
      * `ControlledVehicle.remaing_route_nodes()`
      * Punishment based on collision.
      * Right-lane reward
