### ISSUE TITLE
Make `weighted-two-way-v0` environment

### ISSUE THREAD

**Issue by GustavGroenborg** [GustavGroenborg/HighwayEnv#7]
Make an environment to simulate the ego-vehicle driving along a two-way road. This environment is already partly made in `envs/two_way_env.py`, but several problems exists with the current implementation:
* The ego-vehicle tends to drive on the left side of the road, which is problematic for the life expectancy of the ego-vehicle.
   * This can _probably_ be mitigated by increasing the right-lane reward and looking into the logic of the left-lane reward.
* The current environment is unweighted and lacks a lane type.

## Tasks
- [x] Derive from `TwoWayEnv`
- [x] Override the following functions:
   - [x] `TwoWayEnv._reward(action)`
   - [x] `TwoWayEnv._rewards(action)`
   - [x] `TwoWayEnv._create_road(...)`
   - [x] `TwoWayEnv._create_vehicles()`
- [x] Use `WeightedRoadnetwork` to construct the graph.
- [ ] Make spawning algorithm, to spawn a random number of vehicles going in both directions
   - [ ] Vehicles **must** be spawned both ahead and behind of the ego-vehicle, in the same lane as the ego-vehicle
   - [ ] Vehicles must be spawned on both lanes
   - [ ] The ego vehicle must be able to spawn both in the left, and in the right lane, such that it can be trained to drive in both directions
   - [ ] The number of vehicles spawned must be based on the instance key-value argument `TwoWayEnv.config["vehicles_count"]`
- [x] Add lane-type to each edge.
- [x] Add weight to each edge.
- [ ] Make a `networkx` drawing over the environment.
   * Look to `envs/env_drawing.ipynb` for inspiration.
- [ ] Write the reward function.
   * It could possibly include the following:
      * `ControlledVehicle.headway_evaluation()`
      * Punishment based on collision.
      * Right-lane reward, or driving-lane direction reward.
