### ISSUE TITLE
Make `weighted-highway-v0` environment

### ISSUE THREAD

**Issue by GustavGroenborg** [GustavGroenborg/HighwayEnv#9]
Make a weighted highway environment that simply derives from the current implementation of the highway environment in `envs/highway_env.py`.

## Tasks
- [x] Derive from `HighwayEnv`.
- [x] Override the function `HighwayEnv._create_road()`.
- [x] The weight must be added, the value is completely arbitrary.
- [x] Add the appropriate lane type.
